### ISSUE TITLE
割り込みバグ修正

### ISSUE THREAD

**Issue by yu-tanabe** [tmori/athrill#1]
athrill\trunk\src\device\intc\target\v850e2m\intc.c
intc_raise関数
ecrレジスタのデータを扱う変数のサイズが正しくは32bit
EICCのマスクは「FF00」⇒「FFFF0000」となる

**Comment by tmori** [comment]
バグ報告ありがとうございます．
修正しましたので，ご確認ください．

https://github.com/tmori/athrill/commit/301e6e341e208eb48fd7cac79c39b611af08c4e7
