### ISSUE TITLE
VSCODEのリモート開発機能を使ってwslに接続すると、listコマンドでVSCODEを起動できない

### ISSUE THREAD

**Issue by ykominami** [tmori/athrill#20]
現在では、wslにLinux向けVSCODEをインストールするより、リモート開発機能拡張をを使って、wslに接続することが推奨されています。
wslにはvscode-serverがインストールされます。
現在のathrill/bin/linux/geany.shでは、codeコマンドが存在しなければエラーになります。
リモート開発機能拡張を使っても、listコマンドで表示して欲しい。

**Comment by takasehideki** [comment]
下記に転記
https://github.com/toppers/athrill/issues/6
