### ISSUE TITLE
ftコマンドで直近の関数スタックからも表示して欲しい。

### ISSUE THREAD

**Issue by ykominami** [tmori/athrill#22]
現在のftコマンドでは、個数を指定すると、常に1番のスタックから表示されます。
これとは逆に、直近のスタックから表示される（番号が大きいほうが先頭にくるままでいいです）オプション、または別コマンドが欲しいです。

**Comment by tmori** [comment]
すみません，ご要望の内容が把握できないでおります．
直近のスタックの定義をお教えいただけますでしょうか．

現状のftコマンドの仕様は以下の通りになります．

athrillは，CPUが実行した命令アドレスに対して，dwarfデバッグ情報をもとに関数マッピング可能なものについて，その関数およびスタック情報をロギングします．

ftコマンドでは，上記ログ情報を，最新ログから古い方向に順番に表示します．

直近のスタックの定義が，最新，つまりデバッグしている時点のスタックでしたら，ご要望にかなっているかと思いますが，いかがでしょうか．

**Comment by ykominami** [comment]
このissueを書いたときは以下のような状況でした。
一番古いものを0版とすると、その次は1番、最新を10番とすると、
ft 5は
[4]
[3]
[2]
[1]
[0]

ft 9は
[8]
[7]
[6]
[5]
[4]
[3]
[2]
[1]
[0]
と表示されました。

現在のリビジョンでの振舞は、未確認です。

自分の要望は以下のようになってほしいということです。
ft 5は
[10]
[9]
[8]
[7]
[6]

ft 9は
[10]
[9]
[8]
[7]
[6]
[5]
[4]
[3]
[2]

**Comment by ykominami** [comment]
以下のcommitを適用した状態でのftコマンドの挙動を示します。

87c9ec3 fix #26

[DBG>ft 5
core0: <_kernel_stack_MAIN_TASK       (0xf7c)> [  4] <0x000> _kernel_tmevt_up
core0: <_kernel_stack_MAIN_TASK       (0xf7c)> [  3] <0x034> _kernel_tmevtb_enqueue
core0: <_kernel_stack_MAIN_TASK       (0xf88)> [  2] <0x07c> _kernel_make_wait_tmout
core0: <_kernel_stack_MAIN_TASK       (0xfbc)> [  1] <0x09c> tslp_tsk
core0: <_kernel_stack_MAIN_TASK       (0xf80)> [  0] <0x000> set_intpri
[DBG>ft 10
core0: <_kernel_stack_MAIN_TASK       (0xf88)> [  9] <0x000> _kernel_tmevtb_enqueue
core0: <_kernel_stack_MAIN_TASK       (0xf7c)> [  8] <0x000> _kernel_update_current_evttim
core0: <_kernel_stack_MAIN_TASK       (0xf78)> [  7] <0x000> _kernel_target_hrt_get_current
core0: <_kernel_stack_MAIN_TASK       (0xf78)> [  6] <0x008> _kernel_update_current_evttim
core0: <_kernel_stack_MAIN_TASK       (0xf7c)> [  5] <0x00c> _kernel_tmevtb_enqueue
core0: <_kernel_stack_MAIN_TASK       (0xf7c)> [  4] <0x000> _kernel_tmevt_up
core0: <_kernel_stack_MAIN_TASK       (0xf7c)> [  3] <0x034> _kernel_tmevtb_enqueue
core0: <_kernel_stack_MAIN_TASK       (0xf88)> [  2] <0x07c> _kernel_make_wait_tmout
core0: <_kernel_stack_MAIN_TASK       (0xfbc)> [  1] <0x09c> tslp_tsk
core0: <_kernel_stack_MAIN_TASK       (0xf80)> [  0] <0x000> set_intpri
[DBG>

デバッグしている時点のスタックを示すためにft 10000を実行すると以下のようになります。
[DBG>ft 10000
core0: <_kernel_stack_TSKID_tTask_LogTask_Task(0xf78)> [1023] <0x03c> syslog_printf
core0: <_kernel_stack_TSKID_tTask_LogTask_Task(0xf78)> [1022] <0x000> logtask_putc
core0: <_kernel_stack_TSKID_tTask_LogTask_Task(0xf70)> [1021] <0x000> tSerialPortMain_eSerialPort_write
core0: <_kernel_stack_TSKID_tTask_LogTask_Task(0xf50)> [1020] <0x000> sns_dpn
(以下略)

要望は、ft 4としたら[1023]から[1020]が上記ft 10000としたときと同じ順番に表示されることです。
